// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCrPr7fzT94P7NpdsM0IbXQL4GQDnhoo',
    appId: '1:1084517688319:web:d10d581d3d7c26fe21fdca',
    messagingSenderId: '1084517688319',
    projectId: 'symmetry-news-app-3ca98',
    authDomain: 'symmetry-news-app-3ca98.firebaseapp.com',
    storageBucket: 'symmetry-news-app-3ca98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFi-6ZnY5AftPI0KkkSfBIQBIpHqSPegc',
    appId: '1:1084517688319:android:35771bcab962ce9221fdca',
    messagingSenderId: '1084517688319',
    projectId: 'symmetry-news-app-3ca98',
    storageBucket: 'symmetry-news-app-3ca98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEnzUEE00G5KVNizbrGxPLKgZOSuSRyCk',
    appId: '1:1084517688319:ios:7dbc65a4f194511a21fdca',
    messagingSenderId: '1084517688319',
    projectId: 'symmetry-news-app-3ca98',
    storageBucket: 'symmetry-news-app-3ca98.firebasestorage.app',
    iosBundleId: 'com.example.newsAppCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEnzUEE00G5KVNizbrGxPLKgZOSuSRyCk',
    appId: '1:1084517688319:ios:7dbc65a4f194511a21fdca',
    messagingSenderId: '1084517688319',
    projectId: 'symmetry-news-app-3ca98',
    storageBucket: 'symmetry-news-app-3ca98.firebasestorage.app',
    iosBundleId: 'com.example.newsAppCleanArchitecture',
  );
}
